"""Markdown report writer for the first HEIR workload."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _value(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.6f}"
    return str(value)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    lines.extend("| " + " | ".join(_value(value) for value in row) + " |" for row in rows)
    return "\n".join(lines)


def write_pos_count_report(path: Path, summary: dict[str, Any], preview: list[dict[str, Any]]) -> None:
    status = summary.get("backend_status", "unknown")
    correctness = summary.get("correctness", {})
    proof = summary.get("heir_result", {}).get("heir_proof", {})
    criteria = [
        ["Plaintext reference recorded", "Pass"],
        ["Applicant IDs excluded from HE tensors", "Pass"],
        ["HEIR-generated CKKS source executed", "Pass" if status == "heir_generated_ckks_completed" else "Not run"],
        ["Accuracy within tolerance", "Pass" if correctness.get("passed") else "Not run"],
        ["Timing and artifact sizes recorded", "Pass"],
    ]
    timings = [[name, seconds] for name, seconds in summary.get("timings_seconds", {}).items()]
    sizes = [[name, size] for name, size in summary.get("artifact_sizes_bytes", {}).items()]
    preview_rows = [
        [row.get("app_index"), row.get("POS_COUNT"), row.get("actual_POS_COUNT", ""), row.get("absolute_error", "")]
        for row in preview[:10]
    ]
    report = f"""# HEIR CKKS benchmark: POS_COUNT

## Status

`{status}`

This benchmark reconstructs the exact count primitive used by the original
feature pipeline:

```python
pos_agg["POS_COUNT"] = pos.groupby("SK_ID_CURR").size()
```

## Acceptance criteria

{_table(["Criterion", "Result"], criteria)}

## Privacy and calculation boundary

- Trusted preparation selects applicants, aligns POS rows, and retains
  `SK_ID_CURR` and `TARGET` under `client_private/`.
- The HE input contains anonymous fixed-shape 0/1 history masks and unit
  weights only.
- The HEIR kernel evaluates `dot_product(history_mask, unit_weights)` under
  CKKS and returns one encrypted count per anonymous applicant.
- Tensor shape and the number of selected applicants remain visible metadata.

## Input scope

{_table(
    ["Measure", "Value"],
    [
        ["Application rows", summary.get("application_rows")],
        ["POS rows scanned", summary.get("pos_rows_scanned")],
        ["Matched POS rows", summary.get("matched_pos_rows")],
        ["Slots per applicant", summary.get("slots_per_application")],
        ["Padding slots", summary.get("padding_slots")],
    ],
)}

## Result preview

{_table(["Anonymous app index", "Plaintext POS_COUNT", "CKKS POS_COUNT", "Absolute error"], preview_rows)}

## HEIR source proof

{_table(
    ["Proof", "Value"],
    [
        ["CKKS-only validation", proof.get("ckks_only", "Not run")],
        ["Generated C++ SHA256", proof.get("heir_output_cpp_sha256", "Not run")],
        ["Generated header SHA256", proof.get("heir_output_h_sha256", "Not run")],
    ],
)}

## Timings

{_table(["Stage", "Seconds"], timings)}

## Artifact sizes

{_table(["Artifact", "Bytes"], sizes)}

## Current limitation

`prepare-only` proves the reference, privacy split, tensor shape, and report
contract. It is not evidence of HE execution. Full completion requires
CKKS-only `heir_output.cpp/h` generated by HEIR; BGV/BFV/BinFHE generated
sources are rejected by the backend.
"""
    path.write_text(report, encoding="utf-8")


def write_function_report(
    path: Path, summary: dict[str, Any], preview: list[dict[str, Any]]
) -> None:
    """Write the common report contract used by all function task adapters."""
    task = summary["task"]
    criteria = [
        ["Source function and lines recorded", "Pass"],
        ["Raw identifiers and TARGET excluded from HE tensors", "Pass"],
        ["Missing values compacted by client", "Pass"],
        ["Reusable kernel contracts referenced", "Pass"],
        ["Plaintext source reference and kernel oracle recorded", "Pass"],
        ["HEIR-generated CKKS executed", "Not run"],
    ]
    feature_rows = [
        [feature["name"], ", ".join(feature["operations"]), feature["transform"]]
        for feature in task["features"]
    ] or [["ROW_COUNT", "count", "row occupancy"]]
    preview_rows = [
        [row.get("app_index"), row.get("feature"), row.get("operation"), row.get("value")]
        for row in preview[:12]
    ]
    boundary_rows = [
        ["Client preparation", item] for item in task["client_preparation"]
    ] + [["Excluded", item] for item in task["excluded_outputs"]]
    contract_rows = [
        [
            contract["kernel_id"],
            contract["name"],
            contract["multiplicative_depth"],
            contract["generated_ckks_status"],
        ]
        for contract in summary["kernel_contracts"]
    ]
    report = f"""# HEIR CKKS function benchmark: {task['task_id']} {task['title']}

## Status

`{summary['backend_status']}`

This report covers `{task['function_name']}()` source lines
`{task['source_lines']}`. It prepares a function-specific benchmark over shared
arithmetic kernels; it does not contain copied cryptographic implementation.

## Acceptance criteria

{_table(["Criterion", "Result"], criteria)}

## Source outputs in this task

{_table(["Feature", "Retained operations", "Client transform"], feature_rows)}

Mean and pandas sample variance are trusted post-processing of decrypted
`count`, `sum`, and `sum_squares`. A missing source value is removed during
trusted compaction; HEIR does not detect missingness.

## Reusable kernels

{_table(["ID", "Kernel", "Depth", "Generated CKKS"], contract_rows)}

## Privacy and calculation boundary

{_table(["Boundary", "Decision"], boundary_rows)}

- Prepared tensor CSV files are plaintext client-side staging artifacts and
  must not be sent to the server before encryption.
- Applicant identifiers and TARGET remain under `client_private/`.
- Tensor shape, task name, feature names, and selected applicant count are
  visible benchmark metadata.

## Input scope

{_table(
    ["Measure", "Value"],
    [
        ["Application rows", summary["application_rows"]],
        ["Source rows scanned", summary["source_rows_scanned"]],
        ["Source rows matched", summary["source_rows_matched"]],
        ["Auxiliary rows scanned", summary["auxiliary_rows_scanned"]],
        ["Slots per applicant", summary["slots_per_application"]],
        ["Client-compacted missing values", summary["client_compacted_missing_values"]],
    ],
)}

## Plaintext result preview

{_table(["Anonymous app", "Feature", "Operation", "Value"], preview_rows)}

## Timings

{_table(["Stage", "Seconds"], [[key, value] for key, value in summary["timings_seconds"].items()])}

## Artifact sizes

{_table(["Artifact", "Bytes"], [[key, value] for key, value in summary["artifact_sizes_bytes"].items()])}

## Current limitation

`prepared_only` validates source mapping, client/HE separation, tensor shape,
and plaintext oracles. It is not evidence of encrypted execution. Completion
requires compiling the referenced reusable MLIR with HEIR's CKKS/OpenFHE
pipeline and comparing decrypted outputs with `kernel_oracle.csv`.
"""
    path.write_text(report, encoding="utf-8")
