"""Markdown report writer for the first HEIR workload."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _value(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.6f}"
    return str(value)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    lines.extend("| " + " | ".join(_value(value) for value in row) + " |" for row in rows)
    return "\n".join(lines)


def write_pos_count_report(path: Path, summary: dict[str, Any], preview: list[dict[str, Any]]) -> None:
    status = summary.get("backend_status", "unknown")
    correctness = summary.get("correctness", {})
    proof = summary.get("heir_result", {}).get("heir_proof", {})
    criteria = [
        ["Plaintext reference recorded", "Pass"],
        ["Applicant IDs excluded from HE tensors", "Pass"],
        ["HEIR-generated CKKS source executed", "Pass" if status == "heir_generated_ckks_completed" else "Not run"],
        ["Accuracy within tolerance", "Pass" if correctness.get("passed") else "Not run"],
        ["Timing and artifact sizes recorded", "Pass"],
    ]
    timings = [[name, seconds] for name, seconds in summary.get("timings_seconds", {}).items()]
    sizes = [[name, size] for name, size in summary.get("artifact_sizes_bytes", {}).items()]
    preview_rows = [
        [row.get("app_index"), row.get("POS_COUNT"), row.get("actual_POS_COUNT", ""), row.get("absolute_error", "")]
        for row in preview[:10]
    ]
    report = f"""# HEIR CKKS benchmark: POS_COUNT

## Status

`{status}`

This benchmark reconstructs the exact count primitive used by the original
feature pipeline:

```python
pos_agg["POS_COUNT"] = pos.groupby("SK_ID_CURR").size()
```

## Acceptance criteria

{_table(["Criterion", "Result"], criteria)}

## Privacy and calculation boundary

- Trusted preparation selects applicants, aligns POS rows, and retains
  `SK_ID_CURR` and `TARGET` under `client_private/`.
- The HE input contains anonymous fixed-shape 0/1 history masks and unit
  weights only.
- The HEIR kernel evaluates `dot_product(history_mask, unit_weights)` under
  CKKS and returns one encrypted count per anonymous applicant.
- Tensor shape and the number of selected applicants remain visible metadata.

## Input scope

{_table(
    ["Measure", "Value"],
    [
        ["Application rows", summary.get("application_rows")],
        ["POS rows scanned", summary.get("pos_rows_scanned")],
        ["Matched POS rows", summary.get("matched_pos_rows")],
        ["Slots per applicant", summary.get("slots_per_application")],
        ["Padding slots", summary.get("padding_slots")],
    ],
)}

## Result preview

{_table(["Anonymous app index", "Plaintext POS_COUNT", "CKKS POS_COUNT", "Absolute error"], preview_rows)}

## HEIR source proof

{_table(
    ["Proof", "Value"],
    [
        ["CKKS-only validation", proof.get("ckks_only", "Not run")],
        ["Generated C++ SHA256", proof.get("heir_output_cpp_sha256", "Not run")],
        ["Generated header SHA256", proof.get("heir_output_h_sha256", "Not run")],
    ],
)}

## Timings

{_table(["Stage", "Seconds"], timings)}

## Artifact sizes

{_table(["Artifact", "Bytes"], sizes)}

## Current limitation

`prepare-only` proves the reference, privacy split, tensor shape, and report
contract. It is not evidence of HE execution. Full completion requires
CKKS-only `heir_output.cpp/h` generated by HEIR; BGV/BFV/BinFHE generated
sources are rejected by the backend.
"""
    path.write_text(report, encoding="utf-8")
