"""Markdown report writer for the first HEIR workload."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _value(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.6f}"
    return str(value)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    lines.extend("| " + " | ".join(_value(value) for value in row) + " |" for row in rows)
    return "\n".join(lines)


def write_pos_count_report(path: Path, summary: dict[str, Any], preview: list[dict[str, Any]]) -> None:
    status = summary.get("backend_status", "unknown")
    correctness = summary.get("correctness", {})
    proof = summary.get("heir_result", {}).get("heir_proof", {})
    criteria = [
        ["Plaintext reference recorded", "Pass"],
        ["Applicant IDs excluded from HE tensors", "Pass"],
        ["HEIR-generated CKKS source executed", "Pass" if status == "heir_generated_ckks_completed" else "Not run"],
        ["Accuracy within tolerance", "Pass" if correctness.get("passed") else "Not run"],
        ["Timing and artifact sizes recorded", "Pass"],
    ]
    timings = [[name, seconds] for name, seconds in summary.get("timings_seconds", {}).items()]
    sizes = [[name, size] for name, size in summary.get("artifact_sizes_bytes", {}).items()]
    preview_rows = [
        [row.get("app_index"), row.get("POS_COUNT"), row.get("actual_POS_COUNT", ""), row.get("absolute_error", "")]
        for row in preview[:10]
    ]
    report = f"""# HEIR CKKS benchmark: POS_COUNT

## Status

`{status}`

This benchmark reconstructs the exact count primitive used by the original
feature pipeline:

```python
pos_agg["POS_COUNT"] = pos.groupby("SK_ID_CURR").size()
```

## Acceptance criteria

{_table(["Criterion", "Result"], criteria)}

## Privacy and calculation boundary

- Trusted preparation selects applicants, aligns POS rows, and retains
  `SK_ID_CURR` and `TARGET` under `client_private/`.
- The HE input contains anonymous fixed-shape 0/1 history masks and unit
  weights only.
- The HEIR kernel evaluates `dot_product(history_mask, unit_weights)` under
  CKKS and returns one encrypted count per anonymous applicant.
- Tensor shape and the number of selected applicants remain visible metadata.

## Input scope

{_table(
    ["Measure", "Value"],
    [
        ["Application rows", summary.get("application_rows")],
        ["POS rows scanned", summary.get("pos_rows_scanned")],
        ["Matched POS rows", summary.get("matched_pos_rows")],
        ["Slots per applicant", summary.get("slots_per_application")],
        ["Padding slots", summary.get("padding_slots")],
    ],
)}

## Result preview

{_table(["Anonymous app index", "Plaintext POS_COUNT", "CKKS POS_COUNT", "Absolute error"], preview_rows)}

## HEIR source proof

{_table(
    ["Proof", "Value"],
    [
        ["CKKS-only validation", proof.get("ckks_only", "Not run")],
        ["Generated C++ SHA256", proof.get("heir_output_cpp_sha256", "Not run")],
        ["Generated header SHA256", proof.get("heir_output_h_sha256", "Not run")],
    ],
)}

## Timings

{_table(["Stage", "Seconds"], timings)}

## Artifact sizes

{_table(["Artifact", "Bytes"], sizes)}

## Current limitation

`prepare-only` proves the reference, privacy split, tensor shape, and report
contract. It is not evidence of HE execution. Full completion requires
CKKS-only `heir_output.cpp/h` generated by HEIR; BGV/BFV/BinFHE generated
sources are rejected by the backend.
"""
    path.write_text(report, encoding="utf-8")


def _source_python_excerpt(task: dict[str, Any]) -> str:
    """Return a short source-equivalent pandas pattern for one task report."""
    task_id = task["task_id"]
    if task["function_name"] == "bureau_and_balance":
        if task_id == "B01":
            return """# Source pattern (shortened from lines 91-114)
bureau_agg = bureau.groupby("SK_ID_CURR").agg(num_aggregations)"""
        branch = "Active" if task_id == "B02" else "Closed"
        return f"""# Source pattern (shortened from lines 115-126)
subset = bureau[bureau["CREDIT_ACTIVE_{branch}"] == 1]
subset_agg = subset.groupby("SK_ID_CURR").agg(num_aggregations)"""
    if task["function_name"] == "previous_applications":
        if task_id == "P01":
            return """# Source pattern (shortened from lines 142-162)
prev["APP_CREDIT_PERC"] = prev["AMT_APPLICATION"] / prev["AMT_CREDIT"]
prev_agg = prev.groupby("SK_ID_CURR").agg(num_aggregations)"""
        branch = "Approved" if task_id == "P02" else "Refused"
        return f"""# Source pattern (shortened from lines 163-172)
subset = prev[prev["NAME_CONTRACT_STATUS_{branch}"] == 1]
subset_agg = subset.groupby("SK_ID_CURR").agg(num_aggregations)"""
    if task["function_name"] == "pos_cash":
        if task_id == "POS01":
            return """# Exact source operation (line 193)
pos_agg["POS_COUNT"] = pos.groupby("SK_ID_CURR").size()"""
        return """# Source pattern (shortened from lines 182-191)
pos_agg = pos.groupby("SK_ID_CURR").agg({
    "MONTHS_BALANCE": ["mean"],
    "SK_DPD": ["mean"],
    "SK_DPD_DEF": ["mean"],
})"""
    if task["function_name"] == "installments_payments":
        if task_id == "I01":
            return """# Exact source operation (line 226)
ins_agg["INSTAL_COUNT"] = ins.groupby("SK_ID_CURR").size()"""
        if task_id == "I03":
            return """# Source pattern (shortened from lines 202-216)
ins["PAYMENT_DIFF"] = ins["AMT_INSTALMENT"] - ins["AMT_PAYMENT"]
ins_agg = ins.groupby("SK_ID_CURR").agg({
    "PAYMENT_DIFF": ["mean", "sum", "var"],
})"""
        return """# Source pattern (shortened from lines 203-223)
ins["PAYMENT_PERC"] = ins["AMT_PAYMENT"] / ins["AMT_INSTALMENT"]
ins["DPD"] = (ins["DAYS_ENTRY_PAYMENT"] - ins["DAYS_INSTALMENT"]).clip(lower=0)
ins_agg = ins.groupby("SK_ID_CURR").agg(aggregations)"""
    if task_id == "C01":
        return """# Exact source operation (line 240)
cc_agg["CC_COUNT"] = cc.groupby("SK_ID_CURR").size()"""
    return """# Source pattern (shortened from lines 236-238)
cc = cc.drop(["SK_ID_PREV"], axis=1)
cc_agg = cc.groupby("SK_ID_CURR").agg(["mean", "sum", "var"])"""


def _benchmark_preparation_excerpt(task: dict[str, Any]) -> str:
    branch = ""
    if task["branch_column"]:
        branch = (
            f'branch_mask = 1.0 if row["{task["branch_column"]}"] '
            f'== "{task["branch_value"]}" else 0.0\n'
        )
    else:
        branch = "branch_mask = 1.0\n"
    if task["kind"] == "count":
        return f"""# Client Python, simplified from prepare_function_task()
rows = rows_grouped_by_anonymous_applicant
history_mask = [1.0] * len(rows)  # then zero-pad to fixed width

# HE input per applicant: encrypted history_mask and encrypted unit_weights
# K01 reference: sum(history_mask[i] * unit_weights[i])"""
    if task["kind"] == "difference_moments":
        return f"""# Client Python, simplified from prepare_function_task()
for row in rows_grouped_by_anonymous_applicant:
    if row_has_both_numeric_inputs(row):
        left.append(float(row["AMT_INSTALMENT"]))
        right.append(float(row["AMT_PAYMENT"]))
        {branch.rstrip()}
# left/right/branch_mask are zero-padded and encrypted."""
    return f"""# Client Python, simplified from prepare_function_task()
for row in rows_grouped_by_anonymous_applicant:
    value = client_prepare_numeric_value(row)  # ratio/clipping when configured
    if value is not None:                       # missing values are compacted here
        values.append(value)
        {branch.rstrip()}
# values and branch_mask are zero-padded and encrypted."""


def _kernel_excerpt(kernel_id: str) -> str:
    examples = {
        "K01": """# K01 dot_product_ct_ct, simplified
result = 0.0
for i in range(width):
    result += left[i] * right[i]""",
        "K02": """# K02 moments, simplified
count = total = sum_squares = 0.0
for i in range(width):
    count += mask[i]
    total += mask[i] * values[i]
    sum_squares += mask[i] * values[i] * values[i]

# Client after decryption:
mean = total / count
sample_var = (sum_squares - total * total / count) / (count - 1)""",
        "K03": """# K03 difference_moments, simplified
count = total = sum_squares = 0.0
for i in range(width):
    difference = left[i] - right[i]
    count += mask[i]
    total += mask[i] * difference
    sum_squares += mask[i] * difference * difference""",
    }
    return examples[kernel_id]


def write_function_report(
    path: Path, summary: dict[str, Any], preview: list[dict[str, Any]]
) -> None:
    """Write the common report contract used by all function task adapters."""
    task = summary["task"]
    criteria = [
        ["Source function and lines recorded", "Pass"],
        ["Raw identifiers and TARGET excluded from HE tensors", "Pass"],
        ["Missing values compacted by client", "Pass"],
        ["Reusable kernel contracts and MLIR builders referenced", "Pass"],
        ["Plaintext source reference and kernel oracle recorded", "Pass"],
        ["HEIR-generated CKKS executed", "Not run — this is a prepare-only run"],
    ]
    feature_rows = [
        [feature["name"], ", ".join(feature["operations"]), feature["transform"]]
        for feature in task["features"]
    ] or [["ROW_COUNT", "count", "row occupancy"]]
    preview_rows = [
        [row.get("app_index"), row.get("feature"), row.get("operation"), row.get("value")]
        for row in preview[:12]
    ]
    boundary_rows = [
        ["Client preparation", item] for item in task["client_preparation"]
    ] + [["Excluded", item] for item in task["excluded_outputs"]]
    contract_rows = [
        [
            contract["kernel_id"],
            contract["name"],
            contract["multiplicative_depth"],
            contract["generated_ckks_status"],
        ]
        for contract in summary["kernel_contracts"]
    ]
    kernel_code = "\n\n".join(
        f"### {contract['kernel_id']} `{contract['name']}`\n\n```python\n"
        f"{_kernel_excerpt(contract['kernel_id'])}\n```"
        for contract in summary["kernel_contracts"]
    )
    report = f"""# HEIR CKKS function benchmark: {task['task_id']} {task['title']}

## Status

`{summary['backend_status']}` means the trusted-client Python preparation ran,
but no homomorphic-encryption program ran.

Completed in this run:

- Read the source CSV and select the benchmark applicants.
- Apply documented client preparation, pack and zero-pad numeric tensors.
- Calculate the plaintext source reference and the expected reusable-kernel
  outputs in `kernel_oracle.csv`.
- Write the tensor manifest and this Markdown report.

Not executed in this run:

- `heir-opt`, `heir-translate`, or HEIR-generated C++.
- CKKS context/key generation, encryption, encrypted evaluation, decryption,
  CKKS error measurement, or OpenFHE timing.

So `prepared_only` is a valid preparation/oracle benchmark, not a partial or
successful encrypted computation.

## Source Python and benchmark mapping

This task covers `{task['function_name']}()` source lines `{task['source_lines']}`.
The following is a shortened source-equivalent pattern; the complete list of
retained fields is in the next section.

```python
{_source_python_excerpt(task)}
```

The benchmark-specific client preparation is implemented by
`code/heir/function_benchmark.py::prepare_function_task()` using the task
definition in `code/heir/workloads/`.

```python
{_benchmark_preparation_excerpt(task)}
```

## Acceptance criteria

{_table(["Criterion", "Result"], criteria)}

## Source outputs in this task

{_table(["Feature", "Retained operations", "Client transform"], feature_rows)}

Mean and pandas sample variance are trusted post-processing of decrypted
`count`, `sum`, and `sum_squares`. A missing source value is removed during
trusted compaction; HEIR does not detect missingness.

## Reusable kernels

{_table(["ID", "Kernel", "Depth", "Generated CKKS"], contract_rows)}

## Simplified HEIR arithmetic

The following snippets are the arithmetic contracts represented by the reusable
MLIR builders. They explain the intended encrypted calculation; the snippets
themselves are not the encrypted backend.

{kernel_code}

## Privacy and calculation boundary

{_table(["Boundary", "Decision"], boundary_rows)}

- Prepared tensor CSV files are plaintext client-side staging artifacts and
  must not be sent to the server before encryption.
- Applicant identifiers and TARGET remain under `client_private/`.
- Tensor shape, task name, feature names, and selected applicant count are
  visible benchmark metadata.

## Input scope

{_table(
    ["Measure", "Value"],
    [
        ["Application rows", summary["application_rows"]],
        ["Source rows scanned", summary["source_rows_scanned"]],
        ["Source rows matched", summary["source_rows_matched"]],
        ["Auxiliary rows scanned", summary["auxiliary_rows_scanned"]],
        ["Slots per applicant", summary["slots_per_application"]],
        ["Client-compacted missing values", summary["client_compacted_missing_values"]],
    ],
)}

## Plaintext result preview

{_table(["Anonymous app", "Feature", "Operation", "Value"], preview_rows)}

## Timings

{_table(["Stage", "Seconds"], [[key, value] for key, value in summary["timings_seconds"].items()])}

## Artifact sizes

{_table(["Artifact", "Bytes"], [[key, value] for key, value in summary["artifact_sizes_bytes"].items()])}

## Current limitation

`prepared_only` validates source mapping, client/HE separation, tensor shape,
and plaintext oracles. It is not evidence of encrypted execution. Completion
requires compiling the referenced reusable MLIR with HEIR's CKKS/OpenFHE
pipeline and comparing decrypted outputs with `kernel_oracle.csv`.
"""
    path.write_text(report, encoding="utf-8")
